# Arquivo YAML para o Deployment da API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api-k8s-mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-k8s-mysql
  template:
    metadata:
      labels:
        app: api-k8s-mysql
    spec:
      containers:
        - name: api-container
          image: tech_challenge_product:fiap-k8s
          ports:
            - containerPort: 8080
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql-ext-service

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password
---
# Serviço para a API
apiVersion: v1
kind: Service
metadata:
  name: api-crud-svc
spec:
  selector:
    app: api-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
